# Generated by Django 4.1 on 2022-11-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rang', models.CharField(choices=[('m. dr.', 'Main Doctor'), ('dr.', 'Doctor'), ('n.', 'Nurce'), ('intern', 'Intern')], default='intern', max_length=50)),
                ('sex', models.CharField(choices=[('MR', 'man'), ('MS', 'woman')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(default='123@clinic.com', max_length=254)),
                ('experience', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('speciality', models.CharField(choices=[('Allergy and immunology', 'Allergy and immunology'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Diagnostic radiology', 'Diagnostic radiology'), ('Emergency medicine', 'Emergency medicine'), ('Family medicine', 'Family medicine'), ('Internal medicine', 'Internal medicine'), ('Medical genetics', 'Medical genetics'), ('Neurology', 'Neurology'), ('Nuclear medicine', 'Nuclear medicine'), ('Obstetrics and gynecology', 'Obstetrics and gynecology'), ('Ophthalmology', 'Ophthalmology'), ('Pathology', 'Pathology'), ('Pediatrics', 'Pediatrics'), ('Preventive medicine', 'Preventive medicine'), ('Psychiatry', 'Psychiatry'), ('Radiation oncology', 'Radiation oncology'), ('Surgery', 'Surgery'), ('Urology', 'Urology')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.TextField(default=111, max_length=5)),
                ('description', models.CharField(blank=True, help_text='Information about doctor', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_hospital.doctor')),
                ('hospital_department', models.ManyToManyField(to='new_hospital.medical_speciality')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.ManyToManyField(to='new_hospital.medical_speciality'),
        ),
    ]
