# Generated by Django 4.1 on 2022-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rang',
            field=models.CharField(choices=[('m. dr.', 'Main Doctor'), ('dr.', 'Doctor'), ('n.', 'Nurce'), ('i.', 'Intern')], default='intern', max_length=50),
        ),
    ]
