# Generated by Django 4.1 on 2022-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_hospital', '0002_alter_doctor_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rang',
            field=models.CharField(choices=[('m. dr.', 'Main Doctor'), ('dr.', 'Doctor'), ('n.', 'Nurse'), ('i.', 'Intern')], default='intern', max_length=50),
        ),
    ]
