# Generated by Django 4.1 on 2022-11-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_hospital', '0003_alter_doctor_rang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ('doctor',)},
        ),
    ]
